name: test_env_glidertools
channels:
  - conda-forge
dependencies:
  - numexpr
  - netCDF4
  - pandas
  - xarray >=2022.10.0
  - numpy
  - scikit-learn
  - scipy
  - tqdm
  - matplotlib
  - gsw
  - skyfield
  - pip
  - pip:
    - seawater
    - codecov
    - pytest-cov
    - pytest-xdist
